### ISSUE TITLE
Based on known algorithm 

### ISSUE THREAD

**Issue by usergoodvery** [dbittman/waitfree-mpsc-queue#1]
Hi
Is this implementation based on published algorithm? Seems too straightforward to be true, not withstanding Mpsc has simpler semantics...

**Comment by dbittman** [comment]
There may be a published algorithm, but this one was written in isolation (I whiteboarded it and wrote it). I have not _proven_ that it is correct for the domain of multithreading that it is defined for, but I believe it is correct, and I have tested it.

Could you elaborate?

**Comment by usergoodvery** [comment]
I don't have specific issues to point out, as I have not rigorously looked at the underlying assumptions, but on surface level they look pragmatic and instinctive for a basic MPSC. The general thing with lockless based designs is that even the ones which are based on published algorithms can have (subtle, especially ABA) issues, hence why I was looking to see if this was implemented on the back of some known formal proof of correctness, which generally means one can take risks in terms of adopting it for their needs.

So far the only lockless design that I have adopted wholeheartedly is single-producer-single-consumer queue, also known as Lamport. This primitive is so useful in multi threaded design if you are imaginative enough, and also has formal proof of correctness which is peer-reviewed. You'd think you don't need that for such a simple semantic, but you actually you do...

You may want to look at some of the published literature in this area
There are some useful ref points here https://github.com/rigtorp/awesome-lockfree

**Comment by dbittman** [comment]
Of course. I implemented this as a fun exercise to see if I could come up with a solution without looking at published work, and for use in my own personal projects. As for ABA, I believe that the limited comparisons that the code does removes that issue (it only ever compares a pointer to NULL, for example, and avoids the additional complexities introduced by CAS). Though, like I said, there's nothing formally proven in here. Of course, any client code using this library may run into ABA, but that's out of scope! This code will easily go wrong if used wrong.

I've used a SPSC queue in some of my projects before as well. And yes, I'm well aware of the need for formally proving things, especially when doing lock-free programming.

Yes, I've seen that repo and the items it links to. It's pretty good. The talks by Herb Sutter I found particularly interesting.

**Comment by dbittman** [comment]
Thanks for reminding me of that repo, though! There are some things in there I'd meant to check out and forgot to, and I missed some of the later 2016 stuff.

**Comment by usergoodvery** [comment]
Thanks I think you've done well with this piece; some of the simplifying assumptions you have made allowed you to tackle he problem in a concise  way. But as you say, users must consider the broader issues.

**Comment by treeowl** [comment]
FWIW, ABA should be fairly easy to avoid in a single-consumer structure. The ABA problem tends to involve a node being removed and then reintroduced (with different contents) by one thread while another is trying to remove it. When there's only one consumer, everyone else is just trying to link things on, which tends to be easier for CAS.
