### ISSUE TITLE
Head overflow

### ISSUE THREAD

**Issue by tomeksowi** [dbittman/waitfree-mpsc-queue#11]
I believe `mpscq_enqueue` will have a problem when `head` overflows as `SIZE_T_MAX % q->max` and `0 % q->max` don't have to point to adjacent elements in the circular buffer.

This wouldn't be a problem if queue capacity was a power of two but `mpscq_create` doesn't require that.

**Comment by dbittman** [comment]
yes you're right this was part of the design from the start, it being missing from the docs is an oversight. If I find time and no one does it first I'll put a check in the create function to enforce it.
